# Generated by Django 3.2.3 on 2021-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField(blank=True, editable=True, null=True)),
                ('artist', models.CharField(blank=True, default='unknown', max_length=255, null=True, verbose_name='artist name')),
                ('title', models.CharField(blank=True, default='unknown', max_length=255, null=True, verbose_name='track title')),
            ],
        ),
    ]
