# Generated by Django 3.2.3 on 2021-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
