# Generated by Django 3.2.3 on 2021-05-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0002_alter_track_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name_plural': 'Tracks'},
        ),
    ]
